

#Even Fibonacci
# https://projecteuler.net/problem=2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#generate fibonachi

array = [1,2]

#generate fibonachi series
while array[-1]<=4000000:
	last = array[-1]
	previous =  array[-2]
	new = last + previous
	array.append(new)


#find sum of even numbers
new_array = []
for i in array:
	if i % 2 == 0 and i < 4000000:
		new_array.append(i)


#print result
result = sum(new_array)
print result